### ISSUE TITLE
Works great.

### ISSUE THREAD

**Issue by henrikl2000** [eschava/FireNotify-Android#1]
Would be great with a notify sound on Android on new message arrival.

**Comment by eschava** [comment]
It uses notification functions provided by Android
Does the sound differ from notifications from other apps?

**Comment by henrikl2000** [comment]
I have no sound on notifications from FireNotify. Maybe my phone is the issue. When I receive an sms there is a sound.

**Comment by eschava** [comment]
Please check your phone or Android notification settings for FireNotify
Works nicely on my phone
