### ISSUE TITLE
Image and icon are not shown

### ISSUE THREAD

**Issue by sydspost** [eschava/FireNotify-Android#2]
My msg.payload:

msg.payload = {
	"data": 
	{
	    "title": "Bel gaat",
		"text": "Gauw naar de deur",
		"image": "http://192.168.X.X/wc.jpg",
		"icon": "https://check.netatmo.com/images/netatmo-doorbell.svg"
	},
	"to" : "XXX",
	"priority" : "high"
}

return msg;

Both image and icon are not shown in the notification and neither in the FireNotify app

**Comment by eschava** [comment]
I think there are two different reasons
For "image" it won't work outside of your local network. Or it doesn't work in the local network as well?
For "icon" - SVG format is not supported natively by application, only jpg/png/gif/bmp

**Comment by sydspost** [comment]
eschava,

Put the image and an icon (in jpg format 72x72 pixels) on my webserver which is accessibel outside my local network, everything works fine now.

Thx
