### ISSUE TITLE
Only basic functionality working (no images, no actions)

### ISSUE THREAD

**Issue by erikm30** [eschava/FireNotify-Android#3]
Whatever I do, I cannot get the image nor the actions to work, even when directly copying the code from the examples I found scattered over the web.

Here is an example:

{
    "registration_ids": [
        "xxx", "yyy"
    ],
    "image": "https://www.fujifilm.com/products/digital_cameras/x/fujifilm_x_t1/sample_images/img/index/ff_x_t1_001.JPG",
    
    "data": {
        "text": "Test Notification",
        "title": "From NodeRed"
    },
    

    "actions": [
        {
            "title": "Press me",
            "data": {
                "action": "pressed"
            }
        }
    ]
}

Any idea what is wrong ? Maybe newer Android Versions have an issue ?

**Comment by eschava** [comment]
I've tried to send a notification with your image:

```
payload = {
    'registration_ids': [
        'mmmmeeee'
    ],
    'priority': 'high',
    'data':  {
        'text':  "Test",
        'image': 'https://www.fujifilm.com/products/digital_cameras/x/fujifilm_x_t1/sample_images/img/index/ff_x_t1_001.JPG',
    },
}
```

And got the notification immediately:

![image](https://user-images.githubusercontent.com/147348/106772180-6c903280-6648-11eb-9027-9c7b55f08ebd.png)

**Comment by eschava** [comment]
Actions:
```
payload = {
    'registration_ids': [
        'mmmmeeee'
    ],
    'priority': 'high',
    'data':  {
        'text':  "Test",
        'actions': [
            {'title': 'React', 'data': {"action": "press"}},
            {'title': 'Reply', 'reply': True},
            {'title': 'Dismiss', 'dismiss': True},
        ]
    },
}
```

**Comment by erikm30** [comment]
Thanks, that works - maybe adapt the readme to make it more clear that both "actions" as well as "image" goes under the data - that is what I have missed.
Will close the topic.
